@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

!include FONTAWESOME/server.puml
!include FONTAWESOME/envelope.puml
!include FONTAWESOME/mobile_alt.puml
!include FONTAWESOME/desktop.puml
!include FONTAWESOME/database.puml
!include FONTAWESOME/project_diagram.puml

LAYOUT_TOP_DOWN()
' LAYOUT_AS_SKETCH()
' LAYOUT_WITH_LEGEND()

scale 2

title Diagrama de Infraestructura

System_Boundary(a1, "Client App") {
  Person(spa, "Single Page Application", "", "desktop")
  Person(ma, "Mobile App", "", "mobile_alt")
}

System_Boundary(b1, "Server Process") {
    System(backend_webapp, "WEB Application", "", "server")
    System(backend_api, "API", "", "server")
}

Container(proxiDb, "ProxiSQL", "", "", "project_diagram")

System_Boundary(c1, "Database Cluster") {
    ContainerDb(node1, "Node1", "", "", "database")
    ContainerDb(node2, "Node2", "", "", "database")
    ContainerDb(node3, "Node3", "", "", "database")
}

Rel(ma, backend_api, "Uses", "HTTPS")
Rel(spa, backend_webapp, "Uses", "HTTPS")
Rel(backend_api, proxiDb, "Uses", "async, JSON/HTTPS")
Rel(backend_webapp, proxiDb, "Uses", "async, JSON/HTTPS")

Rel(proxiDb, node1, "Uses", "")
Rel(proxiDb, node2, "Uses", "")
Rel(proxiDb, node3, "Uses", "")

Rel_Back_Neighbor(node1, node2, "", "sync")
Rel_Back_Neighbor(node2, node3, "", "sync")
Rel_Back_Neighbor(node2, node1, "", "")
Rel_Back_Neighbor(node3, node2, "", "")

@enduml