@startuml

' Definición de entidades
entity "Roles" as roles {
    id : INT <<PK>>
    nombre : STRING
    descripcion : STRING
    es_administrador : STRING
    gestiona_noticias_eventos : STRING
    gestiona_contactos_enlaces : STRING
}

entity "User" as user {
    * id : INT
    --
    email : STRING
    username : STRING
    password : STRING
}

entity "Transaction" as transaction {
    * id : INT
    --
    amount : DECIMAL
    date : DATE
    description : STRING
}

entity "Category" as category {
    * id : INT
    --
    name : STRING
    description : STRING
}

' Relaciones
user "1" -- "0..*" transaction : "makes"
transaction "0..1" -- "1" category : "classified as"

@enduml
